DROP TABLE IF EXISTS mannings;
DROP TABLE IF EXISTS job_options;
DROP TABLE IF EXISTS options;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS units;

CREATE TABLE units(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_name TEXT NOT NULL
);

CREATE TABLE jobs(
    id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name TEXT NOT NULL
);

CREATE TABLE options(
    id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    option_name TEXT NOT NULL
);

CREATE TABLE jobs_options(
    id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id INT NOT NULL,
    option_id INT NOT NULL,
    FOREIGN KEY(job_id) REFERENCES jobs(id),
    FOREIGN KEY(option_id) REFERENCES options(id)
);

CREATE TABLE mannings(
    id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    job_id INT NOT NULL REFERENCES jobs(id),
    unit_id INT NOT NULL REFERENCES units(id),
    job_option_id INT NOT NULL REFERENCES job_options(id)
    
);

-- is_deleted to parent tables
-- created_at, updated_at - add a trigger to oit 
-- add schema