DROP TABLE IF EXISTS mannings;
DROP TABLE IF EXISTS job_options;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS units;

CREATE TABLE units(
    unit_id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(40),
    CONSTRAINT "pk_units" PRIMARY KEY(unit_id)
);

CREATE TABLE jobs(
    job_id  INT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(40) NOT NULL,
    CONSTRAINT "pk_jobs" PRIMARY KEY(job_id)
);

CREATE TABLE roles(
    role_id  INT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(40) NOT NULL,
    CONSTRAINT "pk_roles" PRIMARY KEY(role_id)
);



CREATE TABLE job_options(
    job_option_id  INT GENERATED BY DEFAULT AS IDENTITY,
    job_id INT NOT NULL,
    role_id INT NOT NULL,
    CONSTRAINT "pk_job_options" PRIMARY KEY(job_option_id),
    FOREIGN KEY(job_id) REFERENCES jobs(job_id)
        ON DELETE CASCADE,
    FOREIGN KEY(role_id) REFERENCES roles(role_id)
        ON DELETE CASCADE
);

CREATE TABLE mannings(
    manning_id  INT GENERATED BY DEFAULT AS IDENTITY,
    unit_id INT NOT NULL,
    job_option_id INT NOT NULL,
    CONSTRAINT "pk_mannings" PRIMARY KEY(manning_id),
    FOREIGN KEY(job_option_id) REFERENCES job_options(job_option_id)
        ON DELETE CASCADE,
    FOREIGN KEY(unit_id) REFERENCES units(unit_id)
        ON DELETE CASCADE
);